version: '3.8'

networks:
  api_network:
    driver: bridge

services:

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "3000:3000"
    networks:
      - api_network
    restart: always

  # User Service
  user-service:
    build: ./users-service/.
    depends_on:
      - mongo-user
    networks:
      - api_network
    environment:
      DATABASE_URL: ${MONGO_USER_URI}
    ports:
      - "3001:3001"
    restart: always

  # Streaming Service
  streaming-service:
    build: ./streaming-service/.
    depends_on:
      - mongo-streaming
    networks:
      - api_network
    environment:
      DATABASE_URL: ${MONGO_STREAMING_URI}
    ports:
      - "3003:3003"
    restart: always

  # Video Processing Service
  video-processing-service:
    build: ./video-processing-service/.
    depends_on:
      - mongo-streaming
    networks:
      - api_network
    environment:
      DATABASE_URL: ${MONGO_VIDEO_URI}
    ports:
      - "3002:3002"
    restart: always

  # MongoDB for User Service
  mongo-user:
    image: mongo:latest
    networks:
      - api_network
    volumes:
      - userdb-data:/data/db
    ports:
      - "27017:27017"

  # MongoDB for Streaming Service
  mongo-streaming:
    image: mongo:latest
    networks:
      - api_network
    volumes:
      - streamingdb-data:/data/db
    ports:
      - "27018:27017"

volumes:
  userdb-data:
  streamingdb-data:
