version: '3.8'

networks:
  api_network:
    driver: bridge

services:

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "3000:3000"
    networks:
      - api_network
    restart: always

  # User Service
  user-service:
    build: ./users-service/.
    depends_on:
      - mongo-user
    networks:
      - api_network
    environment:
      DATABASE_URL: ${MONGO_USER_URI}
    ports:
      - "3001:3001"
    restart: always

  # Streaming Service
  streaming-service:
    build: ./streaming-service/.
    depends_on:
      - mongo-streaming
    networks:
      - api_network
    environment:
      DATABASE_URL: ${MONGO_STREAMING_URI}
    ports:
      - "3003:3003"
    restart: always

  # Video Processing Service
  video-processing-service:
    build: ./video-processing-service/.
    depends_on:
      - mongo-streaming
    networks:
      - api_network
    environment:
      DATABASE_URL: ${MONGO_VIDEO_URI}
    ports:
      - "3002:3002"
    restart: always

  # MongoDB pour User Service
  mongo-user:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - userdb-data:/data/db
    ports:
      - "27018:27017"
    networks:
      - api_network

  # MongoDB pour Streaming Service
  mongo-streaming:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - streamingdb-data:/data/db
    ports:
      - "27019:27017"
    networks:
      - api_network

  # Mongo-Express pour User Service
  mongo-express-user:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-user:27017/userdb
      ME_CONFIG_BASICAUTH: "false"
    networks:
      - api_network

  # Mongo-Express pour Streaming Service
  mongo-express-streaming:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-streaming:27017/streamingdb
      ME_CONFIG_BASICAUTH: "false"
    networks:
      - api_network

volumes:
  userdb-data:
  streamingdb-data:
